/*
 * This source file was generated by the Gradle 'init' task
 */
package java_guessing_game;

import java.util.Random;
import java.util.Scanner;

public class GuessingGame {
    public static void main(String[] args) {
        System.out.println("Welcome to my guessing game!");

        Random randNumGen = new Random();
        Scanner scanner = new Scanner(System.in);

        System.out.println("Guess a number from 0-9: ");
        String guessString = scanner.nextLine();

        int randNum = randNumGen.nextInt(0, 10);
        int guessedInt = Integer.parseInt(guessString);

        if (randNum == guessedInt) {
            System.out.println("Correct! The answer was " + randNum + "! You guessed " + guessedInt + ".");
        } else {
            System.out.println("Incorrect! The answer was " + randNum + "! You guessed " + guessedInt + ".");
        }

        System.out.println("Thanks for playing!");
        
		scanner.close();
    }

    /**
     * This function makes sure that our code will execute correctly.
     * 
     * Our code compiler requires our Java program to output a greeting message.
     * 
     * @return A greeting message for the user to acknowledge.
     */
    public String getGreeting() {
        return "Welcome to my guessing game!";
    }
}