/*
 * This source file was generated by the Gradle 'init' task
 */
package java_guessing_game;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GuessingGame classUnderTest = new GuessingGame();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
